### ISSUE TITLE
Composter bulk process feature

### ISSUE THREAD

**Issue by Speik** [pl3xgaming/PurpurDocs#13] opened 2021-06-18 06:28 UTC
Hello there. I have an misunderstanding with a composter **sneak-to-bulk-process** feature.

Enabled in **purpur.yml**
```
composter:
        sneak-to-bulk-process: true
```

And when i sneak and right-clicking with stack of sufficient item **nothing** happens.
What am i doing wrong?

**Comment by granny** [comment] 2021-11-16 21:13
Wrong repo for Purpur bug reports. Your issue is a duplicate of pl3xgaming/Purpur#488 and has been fixed since https://github.com/pl3xgaming/Purpur/commit/2824f64e3697ab8e674c7e76c3bbb51f37a3b44b

**Closed by granny** 2021-11-16 21:13 UTC
